### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ktpolanski** [No2Ross/TrAGEDy#1]
Hello,

Could you include a license with your code? This [GitHub documentation page](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) may be helpful. Thanks a lot and sorry for the trouble!

**Comment by No2Ross** [comment]
Hi There!

Added the license, TrAGEDy is of course free to use and do with whatever you'd like!

Having said that, I would wait till we've published before you apply TrAGEDy to your data in any serious capacity or use it in teaching materials, etc. We also need to get better documentation of the functions as well, which will come soon!

Thank you for your interest!

Ross

**Comment by ktpolanski** [comment]
Great, thank you very much! :)
