### ISSUE TITLE
Slingshot pseudotime NA values 

### ISSUE THREAD

**Issue by zhangol** [No2Ross/TrAGEDy#3]
Hi, I tried to use[TrAGEDy](https://github.com/No2Ross/TrAGEDy), the I performed analysis on the dataset and generate two trajectories, when I used the TrAGEDY to compare the two lines, I found the NA of the pseudotime will affect the code running, then I use the pseudotime <- slingPseudotime(sce, na = FALSE), However, I try to find optimal path, it throws me the error. Can I use the TrAGEDy to compare the two trajectories in one dataset. And should I use the same counts matrix for the two trajectories?
<img width="711" alt="image" src="https://github.com/No2Ross/TrAGEDy/assets/137655381/850590e7-ca17-4efc-ae9e-d373adf573a1">
<img width="663" alt="image" src="https://github.com/No2Ross/TrAGEDy/assets/137655381/b91e684f-1fbb-48d5-adc3-775f22e15d16">

**Comment by No2Ross** [comment]
Hi Mingfeng, 

You certainly could use TrAGEDy to compare the trajectories in the same dataset, however I imagine it will just show the two beginning the same and then diverging (like the pseudotime does).

When I ran into NA values, i've subsetted out cells that are only present on the trajectory lineage of interest to me, meaning no NA value cells are left when TrAGEDy is performed.

Next week we can talk about it in person if you are still having trouble.

Ross

**Comment by No2Ross** [comment]
Hi Mingfeng,

I'm at a conference today and yesterday, so it would have to be tomorrow or Thursday. Does that work for you?

Best wishes,
Ross

**Comment by zhangol** [comment]
Hi Ross,

Good morning, I have prepared some questions and want to ask you this afternoon. The problem is the > test <- chunk_node(WT_tree$pseudotime, KO_tree$pseudotime, output_solution_cut)
[1] 0.0001772953
Error in if (is.na(after_nodes) == T) { : the condition has length > 1
Best regards,
Mingfeng


From: No2Ross ***@***.***>
Date: Tuesday, 4 July 2023 at 09:32
To: No2Ross/TrAGEDy ***@***.***>
Cc: Mingfeng Zhang (student) ***@***.***>, Author ***@***.***>
Subject: Re: [No2Ross/TrAGEDy] Slingshot pseudotime NA values (Issue #3)

Hi Mingfeng,

I'm at a conference today and yesterday, so it would have to be tomorrow or Thursday. Does that work for you?

Best wishes,
Ross

**Comment by No2Ross** [comment]
Closed due to inactivity
